### ISSUE TITLE
Starting docker halts

### ISSUE THREAD

**Issue by VincentSC** [instrumentisto/coturn-docker-image#19]
```
vincent@HAL:~$ sudo docker run -d -p 3478:3478 -p 49152-65535:49152-65535/udp instrumentisto/coturn --restart=always --name coTURN --verbose
34fcef6ff8bd6f35d556889594bbde0e558411257ada2c3255ee7b3da73e2ad4
```

And then it does not return to the command line. The created container does not get the provided name, nor has any published ports. I can't exit and need to restart docker to be able to remove the container. What could be the case?

**Comment by tyranron** [comment]
@VincentSC I guess there are problems with wide range of UDP ports mapping. Docker is not quite good with that. I advise you to use `--network=host` for Coturn. All our deployments (even in Kubernetes) use this way.

**Comment by VincentSC** [comment]
`sudo docker run -d -p 3478:3478 -p 49152-65535:49152-65535/udp instrumentisto/coturn --restart=always --name coTURN --network=host --verbose`

Same results.

As I'm using nginx-proxy to define the hostname, I'm not sure this is the right solution for me. will probably go for a normal deployment. If you want me to do certain research, so it can be solved for other/future users, then I'm happy to help. If it's probably my specific environment causing the problem, you can close.

**Comment by tyranron** [comment]
@VincentSC the command you've provided tries to apply `--network=host` flag to the `turnserver` command inside container, but it should go to `docker run` command. The flags order matters here. All the `docker run` flags should go _before_ the image name. Try out this one:
```bash
sudo docker run -d --network=host --restart=always --name coTURN instrumentisto/coturn --verbose
```

I stripped out `-p 3478:3478 -p 49152-65535:49152-65535/udp` flags, because their presence has no sense when `--network=host` is used (you already running container in host network, no ports mapping is required).

**Comment by tyranron** [comment]
@VincentSC I'm closing this for now, due to inactivity. Feel free to reopen if it still matters or is unresolved.

**Comment by VincentSC** [comment]
Yeah, I gave up on this
